language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
cache:
  directories:
    - ~/.m2
install:
  - mvn test-compile -DskipTests=true -B -V -P analysis
script:
  - jdk_switcher use oraclejdk8
  - mvn test jacoco:report -P coverage
  - jdk_switcher use openjdk8
  - mvn test jacoco:report -P coverage
  - jdk_switcher use oraclejdk9
  - mvn test
  - jdk_switcher use oraclejdk10
  - mvn test
  - jdk_switcher use openjdk10
  - mvn test
after_success:
  - mvn coveralls:report -P coverage