language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
cache:
  directories:
    - ~/.m2
install:
  - mvn test-compile -DskipTests=true -B -V -P analysis
script:
  - mvn test jacoco:report -P coverage
after_success:
  - mvn coveralls:report -P coverage