language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - ~/.m2
script: mvn -B clean package -P analysis
install:
    -
after_success:
    - mvn -B clean test jacoco:report coveralls:report -P coverage
